[Main group 13] [feat products]
tryber/sd-010-b-project-delivery-app pull request #185
Opened 2021-11-13 14:25 UTC by FabioMarturanoJr

2021-11-14 13:04 UTC, lucasportella commented on front-end/src/pages/Login.jsx
> +  const [password, setPassword] = useState('$#zebirita#$');
Oi, inicializar o valor do estado com o login do zé birita permite que apenas apertar o botão de login sem escrever nada faça o login com a conta do zé birita. Isso deve ser o que está quebrando o requisito 3.

2021-11-14 13:07 UTC, lucasportella requested changes

2021-11-14 13:07 UTC, lucasportella commented on front-end/src/pages/Login.jsx
> +  const [email, setEmail] = useState('zebirita@email.com');
Oi, inicializar o valor do estado com o login do zé birita permite que apenas apertar o botão de login sem escrever nada faça o login com a conta do zé birita. Isso deve ser o que está quebrando o requisito 3. Sugestão:
`const [email, setEmail] = useState('');`
`const [password, setPassword] = useState('');`

2021-11-15 17:40 UTC, hugolfsimoes commented on front-end/src/pages/Login.jsx
> +  const [email, setEmail] = useState('zebirita@email.com');
Boa Lucas, obrigado pela observação, a gente tinha deixado o Zé birita setado somente para facilitar nos testes manuais. Valeeu.

2021-11-16 22:36 UTC, lucasportella approved these changes

2021-11-16 22:37 UTC, merged