[Group 16][ Reqs 32-35]
tryber/sd-010-b-project-delivery-app pull request #352
Opened 2021-11-20 20:03 UTC by AntenorZapata

## O que esse PR faz?
Cria a rota de atualização do status do pedido. Implementa a lógica de mudança do status em ambas as telas, vendedor e cliente.

## Para entender o fluxo
Quando as páginas de detalhes dos pedidos ('OrderDetails' e 'SellerOrderDetails') é renderizada, é feita uma requisição buscando todas os pedidos com os respectivos 'ids', seja de 'cliente' ou 'vendedor'. Nessa mesma função, um estado de nome 'status', que está no Context, é atualizado com o status do pedido. A função 'handleSaleStatus', que também está no context, é responsável por manipular esse estado de acordo com os botões clicados. Ou seja, se clico no botão 'Preparar pedido', a função faz uma requisição e muda o status para 'Preparando'. Se o botão for o 'Marcar como entregue', muda para 'Entregue' e assim por diante. 

## O que pode ser refeito
Os botões devem ser habilitados ou desabilitados de acordo com o status. Eu criei uma condicional simples para resolver isso. Há soluções melhores.

2021-11-22 17:34 UTC, Renan0211 commented on __tests__/end-to-end/05customer_orders.test.js
> +describe.only(requirement(22), () => {
```suggestion
describe(requirement(22), () => {
```

2021-11-22 19:40 UTC, Renan0211 requested changes

2021-11-22 19:40 UTC, Renan0211 commented on __tests__/end-to-end/05customer_orders.test.js
> +describe.only(requirement(23), () => {
```suggestion
describe(requirement(23), () => {
```

2021-11-22 19:40 UTC, Renan0211 commented on __tests__/end-to-end/08seller_order_details.test.js
> +describe.only(requirement(32), () => {
```suggestion
describe(requirement(32), () => {
```

2021-11-22 19:40 UTC, Renan0211 commented on back-end/src/database/models/salesproduct.js
> +
```suggestion
```

2021-11-22 19:40 UTC, Renan0211 commented on back-end/src/database/models/salesproduct.js
> +
```suggestion
```

2021-11-22 19:40 UTC, Renan0211 commented on front-end/src/api/index.js
> +
```suggestion
```

2021-11-22 19:40 UTC, Renan0211 commented on front-end/src/pages/Products.jsx
> +// import cardFields from '../services/cardFields';
```suggestion
```

2021-11-22 19:40 UTC, Renan0211 commented on front-end/src/pages/SellerOrderDetails.jsx
> +/* eslint-disable no-unused-vars */
```suggestion
```

2021-11-22 19:41 UTC, Renan0211 approved these changes

2021-11-25 18:50 UTC, andredebem requested changes

2021-11-25 18:50 UTC, andredebem commented on front-end/src/api/index.js
> +  baseURL: 'http://localhost:3001/',
```suggestion
  baseURL: 'http://localhost:3001',
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/components/ButtonCustomerOrderDetails.jsx
> +        name="delivired"
```suggestion
        name="delivered"
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/context/productContext.js
> +    if (name === 'delivired') currStatus = 'Entregue';
```suggestion
    if (name === 'delivered') currStatus = 'Entregue';
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/pages/Products.jsx
> +      const total2 = carrinho.reduce((acc, curr) => acc + +curr.price * curr.qty, 0);
```suggestion
      const newTotal = carrinho.reduce((acc, curr) => acc + +curr.price * curr.qty, 0);
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/pages/Products.jsx
> +      setTotal(total2.toFixed(2));
```suggestion
      setTotal(newTotal.toFixed(2));
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/pages/SellerOrderDetails.jsx
> +  const [isFetched, setisFetched] = useState(false);
```suggestion
  const [isFetched, setIsFetched] = useState(false);
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/pages/SellerOrderDetails.jsx
> +      setisFetched(true);
```suggestion
      setIsFetched(true);
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/services/orderTableTitles.js
> +const tableTItles = ['Item', 'Descrição', 'Quantidade',
```suggestion
const tableTitles = ['Item', 'Descrição', 'Quantidade',
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/services/orderTableTitles.js
> +export default tableTItles;
```suggestion
export default tableTitles;
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/services/tableTitles.js
> +const tableTItles = ['Item', 'Descrição', 'Quantidade',
```suggestion
const tableTitles = ['Item', 'Descrição', 'Quantidade',
```

2021-11-25 18:50 UTC, andredebem commented on front-end/src/services/tableTitles.js
> +export default tableTItles;
```suggestion
export default tableTitles;
```

2021-11-25 19:36 UTC, andredebem approved these changes

2021-11-25 19:36 UTC, merged